###
GET http://127.0.0.1:8000/daily-dragon/vocabulary
Authorization: Basic havryliuk <password>

###
OPTIONS http://127.0.0.1:8000/daily-dragon/vocabulary

###
POST http://127.0.0.1:8000/daily-dragon/vocabulary
Authorization: Basic havryliuk <password>

{
    "word": "你好"
}

###
# use tools/encode.py to encode Chinese characters
DELETE http://127.0.0.1:8000/daily-dragon/vocabulary/%E4%BD%A0%E5%A5%BD
Authorization: Basic havryliuk <password>
