###
GET http://127.0.0.1:8000/daily-dragon/vocabulary

###
POST http://127.0.0.1:8000/daily-dragon/vocabulary

{
    "word": "你好"
}

###
DELETE http://127.0.0.1:8000/daily-dragon/vocabulary/%E4%BD%A0%E5%A5%BD
