name: Build Daily Dragon

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - run: pip install -r requirements.txt
      - run: pytest --cov=.

      - name: Prepare AWS Lambda Layer
        run: |
          mkdir -p layer/python
          pip install -r requirements.txt -t layer/python
          cp -r handlers openai_client prompts vocabulary layer/python/
          tree layer/python
          cd layer
          zip -r ../layer.zip .
          cd ..
