name: Deploy Daily Dragon

on: [ push ]

env:
  AWS_REGION: us-east-1
  S3_BUCKET_NAME: daily-dragon-bucket

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          cd src
          pip install -r requirements.txt

      #- name: Run tests
      #  run: pytest --cov=.

      - name: Package source code
        run: |
          cd src
          zip -r ../daily-dragon.zip .

      - name: Upload source code to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 cp daily-dragon.zip s3://$S3_BUCKET_NAME/daily-dragon.zip --region $AWS_REGION
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy CloudFormation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: DailyDragonStack
          template: templates/daily-dragon-stack.yaml
