name: Deploy Daily Dragon

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install -r requirements.txt

      #- name: Run tests
      #  run: pytest --cov=.

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Package Lambda function
        run: |
          mkdir package
          cp daily_dragon_handler.py package/
          cd package
          zip -r ../lambda_function.zip .

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name daily-dragon \
            --zip-file fileb://lambda_function.zip

  deploy-layer:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      layer_arn: ${{ steps.deploy_layer.outputs.layer_arn }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Create Dependencies Layer
        run: |
          mkdir -p python
          pip install -r requirements.txt -t python/
          zip -r dependencies_layer.zip python/

      - name: Deploy Lambda Layer
        id: deploy_layer
        run: |
          LAYER_VERSION_ARN=$(aws lambda publish-layer-version \
            --layer-name daily-dragon-libraries \
            --description "Dependencies for Daily Dragon Lambda" \
            --zip-file fileb://dependencies_layer.zip \
            --compatible-runtimes python3.12 \
            --query LayerVersionArn --output text)
          echo "Published Layer ARN: $LAYER_VERSION_ARN"
          ENCODED_LAYER_ARN=$(echo -n "$LAYER_VERSION_ARN" | base64)
          echo "layer_arn=$ENCODED_LAYER_ARN" >> $GITHUB_OUTPUT

  update-lambda-layer:
    needs: [ deploy, deploy-layer ]
    runs-on: ubuntu-latest
    steps:
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Attach Layer to Lambda
        run: |
          DECODED_LAYER_ARN=$(echo -n "${{ needs.deploy-layer.outputs.layer_arn }}" | base64 --decode)
          echo "Decoded layer ARN: $DECODED_LAYER_ARN"
          aws lambda update-function-configuration \
            --function-name daily-dragon \
            --layers "$DECODED_LAYER_ARN"
